export const ROUTE_STRING = {
  LOGIN: 'login',
  OAUTH_REDIRECT: '/oauth/:provider',
  SIGNUP: 'signup',
  SIGNUP_COMPLETE: 'signup/complete',
  HOME: 'home',
  SUBSCRIPTION: 'subscription',
  RECORDING: 'recording',
  NOTIFICATION: 'notification',
  PROFILE: 'profile',
};

export const ROUTE_URL_FULL = {
  LOGIN: '/' + ROUTE_STRING.LOGIN,
  OAUTH_REDIRECT: '/' + ROUTE_STRING.OAUTH_REDIRECT,
  SIGNUP: '/' + ROUTE_STRING.SIGNUP,
  SIGNUP_COMPLETE: '/' + ROUTE_STRING.SIGNUP_COMPLETE,
  HOME: '/' + ROUTE_STRING.HOME,
  SUBSCRIPTION: '/' + ROUTE_STRING.HOME + '/' + ROUTE_STRING.SUBSCRIPTION,
  RECORDING: '/' + ROUTE_STRING.HOME + '/' + ROUTE_STRING.RECORDING,
  NOTIFICATION: '/' + ROUTE_STRING.HOME + '/' + ROUTE_STRING.NOTIFICATION,
  PROFILE: '/' + ROUTE_STRING.HOME + '/' + ROUTE_STRING.PROFILE,
};
