export const ROUTESTRING = {
  SUBSCRIPTION: 'subscription',
  RECORDING: 'recording',
  NOTIFICATION: 'notification',
  PROFILE: 'profile',
  LOGIN: 'login',
  SIGNUP: 'signup',
};

export const ROUTEURL = {
  SUBSCRIPTION: '/' + ROUTESTRING.SUBSCRIPTION,
  RECORDING: '/' + ROUTESTRING.RECORDING,
  NOTIFICATION: '/' + ROUTESTRING.NOTIFICATION,
  PROFILE: '/' + ROUTESTRING.PROFILE,
  LOGIN: '/' + ROUTESTRING.LOGIN,
  SIGNUP: '/' + ROUTESTRING.SIGNUP,
};
